### ISSUE TITLE
Make pipeline-nodejs-component a publishable npm package

### ISSUE THREAD

**Issue by rsvalerio** [rsvalerio/pipeline-nodejs-main#1]
Npm repo:

https://www.myget.org/F/rsvalerio/npm/

**Comment by Brunoalcau** [comment]
I have don't  permission for publish in that repository

**Comment by MarcosJAOJR** [comment]
é só usar o comando npm pack

**Comment by rsvalerio** [comment]
Link docs

Publish to repo

Make good to be excuted in codeship

**Comment by MarcosJAOJR** [comment]
Step by step in this wiki:
https://github.com/rsvalerio/pipeline-nodejs-main/wiki/How-to-make-and-publish-the-pipeline-nodejs-component-module
