### ISSUE TITLE
Integrate codeship with github, to publish build results back

### ISSUE THREAD

**Issue by rsvalerio** [rsvalerio/pipeline-nodejs-main#4]

**Comment by MarcosJAOJR** [comment]
https://github.com/rsvalerio/pipeline-nodejs-main/wiki/Integrate-codeship-with-github,-to-publish-build-results-back

**Comment by MarcosJAOJR** [comment]
Is this enough to explain how to integrate codeship with github and publish build results back?

**Comment by MarcosJAOJR** [comment]
@rsvalerio

**Comment by rsvalerio** [comment]
Will be done with #2 

This is a free feature from codeship
